name: Stellaris Checksum Patcher

jobs:
  build-linux-nuitka:
    name: "Build: Linux: Nuitka"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.25"
          enable-cache: true
          cache-suffix: nuitka

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
          key: ${{ github.job }}-ccache

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build Nuitka binary
        run: uv run ./builds/build-nuitka.py -p linux

      - name: Upload Nuitka binary
        uses: actions/upload-artifact@v6
        with:
          name: Stellaris-Checksum-Patcher-Nuitka-linux
          path: Stellaris-Checksum-Patcher-Nuitka-linux

  build-linux-pyinstaller:
    name: "Build: Linux: PyInstaller"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.25"
          enable-cache: true
          cache-suffix: pyinstaller

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build PyInstaller binary
        run: uv run ./builds/build-pyinstaller.py -p linux

      - name: Upload PyInstaller binary
        uses: actions/upload-artifact@v6
        with:
          name: Stellaris-Checksum-Patcher-PyInstaller-linux
          path: Stellaris-Checksum-Patcher-PyInstaller-linux

  build-windows-nuitka:
    name: "Build: Windows: Nuitka"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.25"
          enable-cache: true
          cache-suffix: nuitka

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-ccache

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Install Dependency Walker for Nuitka
        uses: onesoftqwq/dependency-walker-installer@v1.0

      - name: Build Nuitka binary
        run: uv run ./builds/build-nuitka.py -p windows

      - name: Upload Nuitka binary
        uses: actions/upload-artifact@v6
        with:
          name: Stellaris-Checksum-Patcher-Nuitka-win.exe
          path: Stellaris-Checksum-Patcher-Nuitka-win.exe

  build-windows-pyinstaller:
    name: "Build: Windows: PyInstaller"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.25"
          enable-cache: true
          cache-suffix: pyinstaller

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build PyInstaller binary
        run: uv run ./builds/build-pyinstaller.py -p windows

      - name: Upload PyInstaller binary
        uses: actions/upload-artifact@v6
        with:
          name: Stellaris-Checksum-Patcher-PyInstaller-win.exe
          path: Stellaris-Checksum-Patcher-PyInstaller-win.exe

on: push